### ISSUE TITLE
Further segmenting transforms directories / Transforms Sets

### ISSUE THREAD

**Issue by maxlandon** [redcanari/canari3#52] opened 2019-01-21 04:33 UTC
Hello, 
First many thanks for this framework.
Second, I have two questions for which the answer, I didn't find.
1) When I create a directory in the transforms directory (for further segmenting), and despite setting the __init__.py file accordingly, any transform will result in an Error "do_transform needs to be implented". 
Is there is any solution to my issue ?
2) I also didn't find how to create sets/subsets of transforms in Maltego. I'll look at the doc again anyway.
Thanks a lot ! 
3) Actually a third question... Is there a way to make transform that simply add dynamic properties without spawning a new entity ? When I do such a transform (basically request.entity += Field(), and return empty response) the Entity on which I ran the transform neither adds the Fields, nor refreshes the existing ones. For this one I searched the doc again and again...

**Comment by cvandeplas** [comment] 2019-02-07 12:18
I'm not sure to understand question 1 and 2, so I'll try to answer question 3.

If I understand your issue correctly, you would like to add data (properties) to the Entity that you use to initiate the transform. 

To do this, just return the new version of the Entity with the added properties.
Ensure you specify the [matching rules](http://www.canariproject.com/en/latest/canari.maltego.message.html#matching-rules) in your entity definition. These are rules that define when two entities should be merged, or be kept separately.

For an example you can have a look at one of my transforms: https://github.com/MISP/MISP-maltego/blob/master/src/MISP_maltego/transforms/common/entities.py#L25

**Comment by allfro** [comment] 2019-02-25 18:57
Regarding adding dynamic fields, this is supported by the framework and documented here:

http://canariproject.com/en/latest/canari.maltego.message.html#adding-additional-information-to-entities

Regarding your first question, I would need to see a PoC to further troubleshoot the issue. I haven't run into this issue myself.

**Comment by allfro** [comment] 2019-02-25 19:08
@maxlandon I am unable to reproduce this issue. Take a look at my shell interaction:

```bash
$ canari create-package foo
Loading Canari configuration file '/Users/ndouba/.canari/canari.conf'
Author name [ndouba]: 
Author email: 
Author email: 
Author email: n@n
Project short description []: 
Would you like an example transform created? [Y/n]: 
creating skeleton in foo
done!
$ cd foo/src
$ mkdir foo/transforms/sub
$ touch foo/transforms/sub/__init__.py
$ mv foo/transforms/helloworld.py foo/transforms/sub/
$ canari list-transforms
Loading Canari configuration file '/Users/ndouba/.canari/canari.conf'
Looking for transforms in foo...
Package loaded.
Canari Transforms:
`- foo.HelloWorld: This transform returns a set of phrases with various salutations to a Person's name.
  `- Maltego identifiers:
    `- foo.HelloWorld applies to maltego.Person in set Foo
$ canari run-transform foo.HelloWorld bob
Loading Canari configuration file '/Users/ndouba/.canari/canari.conf'
Looking for transforms in foo...
Package loaded.
<MaltegoMessage><MaltegoTransformResponseMessage><UIMessages /><Entities><Entity Type="maltego.Phrase"><Value>Hello bob!</Value><Weight>1</Weight></Entity><Entity Type="maltego.Phrase"><Value>This way Mr(s). None!</Value><Weight>1</Weight></Entity><Entity Type="maltego.Phrase"><Value>Hi None!</Value><Weight>1</Weight></Entity></Entities></MaltegoTransformResponseMessage></MaltegoMessage>
$ 
```

**Comment by maxlandon** [comment] 2019-02-25 19:25
`MSM/src/MSM/transforms on  v0.2 [⇡!] 
[I] ➜ ls
common                 msf_db_enumerate.py  __init__.py
msf_db_association.py  msf_db_push_pull.py  __pycache__

MSM/src/MSM/transforms on  v0.2 [⇡!] 
[I] ➜ mkdir metasploit_db                    

MSM/src/MSM/transforms on  v0.2 [⇡!] 
[I] ➜ mv msf_db_association.py metasploit_db 

MSM/src/MSM/transforms on  v0.2 [⇡✘!?] 
[I] ➜ cd ../..            

MSM/src on  v0.2 [⇡✘!?] 
[I] ➜ 

MSM/src on  v0.2 [⇡✘!?] 
[I] ➜ canari list-transforms
Loading Canari configuration file '/home/para/.canari/canari.conf'
Looking for transforms in MSM...
Package loaded.
Canari Transforms:
`- MSM.EnumerateWorkspaceIP:  Enumerates one or more Hosts in Workspace
  `- Maltego identifiers:
    `- MSM.EnumerateWorkspaceIP applies to maltego.Netblock in set MSF | DB | Enumerate
`- MSM.EnumerateHostIP:  Enumerates all IP addresses that match this Host in Metasploit.
  `- Maltego identifiers:
    `- MSM.EnumerateHostIP applies to Generic Host in set MSF | DB | Enumerate
`- MSM.LinuxEnumerateHostIP:  Enumerates all IP addresses that match this Host in Metasploit.
  `- Maltego identifiers:
    `- MSM.LinuxEnumerateHostIP applies to Linux OS in set MSF | DB | Enumerate
`- MSM.WindowsEnumerateHostIP:  Enumerates all IP addresses that match this Host in Metasploit.
  `- Maltego identifiers:
    `- MSM.WindowsEnumerateHostIP applies to Windows OS in set MSF | DB | Enumerate
`- MSM.AppleEnumerateHostIP:  Enumerates all IP addresses that match this Host in Metasploit.
  `- Maltego identifiers:
    `- MSM.AppleEnumerateHostIP applies to Apple OS in set MSF | DB | Enumerate
`- MSM.EnumerateSubnetIP:  Enumerates all other IPv4 Addresses in Subnet
  `- Maltego identifiers:
    `- MSM.EnumerateSubnetIP applies to maltego.IPv4Address in set MSF | DB | Enumerate
`- EnumerateHost:  Enumerates a Host with this IP address
  `- Maltego identifiers:
    `- EnumerateHost applies to maltego.IPv4Address in set MSF | DB | Enumerate
`- EnumerateServices:  Enumerates Services bound to this IP address
  `- Maltego identifiers:
    `- EnumerateServices applies to maltego.IPv4Address in set MSF | DB | Enumerate
`- EnumerateServiceCredentials:  Enumerates Credentials for this Service
  `- Maltego identifiers:
    `- EnumerateServiceCredentials applies to Metasploit Service in set MSF | DB | Enumerate
`- Push Netblock workspace:  Push Maltego properties to Metasploit workspace. NEEDS TO BE A WORKSPACE !
  `- Maltego identifiers:
    `- Push Netblock workspace applies to maltego.Netblock in set MSF | DB | Workspace
`- Push Netblock workspace:  Push Maltego properties to Metasploit workspace. NEEDS TO BE A WORKSPACE !
  `- Maltego identifiers:
    `- Push Netblock workspace applies to Generic Host in set MSF | DB | Workspace
`- Pull Netblock Workspace:  Pull Metasploit properties to Maltego workspace. NEEDS TO BE A WORKSPACE !
  `- Maltego identifiers:
    `- Pull Netblock Workspace applies to maltego.Netblock in set MSF | DB | Workspace
`- Pull Netblock Workspace:  Pull Metasploit properties to Maltego workspace. NEEDS TO BE A WORKSPACE !
  `- Maltego identifiers:
    `- Pull Netblock Workspace applies to Generic Host in set MSF | DB | Workspace
`- Pull Netblock Workspace:  Pull Metasploit properties to Maltego workspace. NEEDS TO BE A WORKSPACE !
  `- Maltego identifiers:
    `- Pull Netblock Workspace applies to Linux OS in set MSF | DB | Workspace
`- Pull Netblock Workspace:  Pull Metasploit properties to Maltego workspace. NEEDS TO BE A WORKSPACE !
  `- Maltego identifiers:
    `- Pull Netblock Workspace applies to Windows OS in set MSF | DB | Workspace
`- Pull Netblock Workspace:  Pull Metasploit properties to Maltego workspace. NEEDS TO BE A WORKSPACE !
  `- Maltego identifiers:
    `- Pull Netblock Workspace applies to Apple OS in set MSF | DB | Workspace
`- MSM.DeleteNetblockWorkspace:  Delete workspace associated to this Netblock. NEEDS TO BE A WORKSPACE !
  `- Maltego identifiers:
    `- MSM.DeleteNetblockWorkspace applies to maltego.Netblock in set MSF | DB | Workspace
`- Delete Host Workspace:  Delete workspace associated to this Netblock. NEEDS TO BE A WORKSPACE !
  `- Maltego identifiers:
    `- Delete Host Workspace applies to Generic Host in set MSF | DB | Workspace
`- Push Host:  Push Maltego properties to Metasploit Host
  `- Maltego identifiers:
    `- Push Host applies to Generic Host in set MSF | DB | Host
`- Pull Host:  Pull Metasploit properties to Maltego Host
  `- Maltego identifiers:
    `- Pull Host applies to Generic Host in set MSF | DB | Host
`- Delete Host:  Delete Metasploit Host associated to this Host Entity
  `- Maltego identifiers:
    `- Delete Host applies to Generic Host in set MSF | DB | Host
`- Push Service:  Push Maltego properties to Metasploit Service
  `- Maltego identifiers:
    `- Push Service applies to Metasploit Service in set MSF | DB | Service
`- Pull Service:  Pull Metasploit properties to Maltego Service
  `- Maltego identifiers:
    `- Pull Service applies to Metasploit Service in set MSF | DB | Service
`- Delete Service:  Delete Metasploit Service associated to this Service Entity
  `- Maltego identifiers:
    `- Delete Service applies to Metasploit Service in set MSF | DB | Service
`- Push Credential: Push Maltego properties to Metasploit Credential.
  `- Maltego identifiers:
    `- Push Credential applies to metasploit.credential.MetasploitCredential in set MSF | DB | Credential
`- Pull Credential:  Pull Metasploit properties to Maltego Credential
  `- Maltego identifiers:
    `- Pull Credential applies to metasploit.credential.MetasploitCredential in set MSF | DB | Credential
`- Delete Credential:  Delete Metasploit Credential associated to this Credential Entity
  `- Maltego identifiers:
    `- Delete Credential applies to metasploit.credential.MetasploitCredential in set MSF | DB | Credential
`
Here is mine: it looks like canari doesn't detect the transforms contained in msf_db_association.py.
I gonna try adding an __init__.py file in the subdirectory right now.

**Comment by maxlandon** [comment] 2019-02-25 19:30
You can find my project at https://github.com/maxlandon/effective-couscous/tree/v0.2 if you want to check it yourself !

**Comment by maxlandon** [comment] 2019-02-25 19:37
Okay it seems to work when I added an __init__.py file in my subdirectory.
But why is it working despite the __init__.py file is empty ?
Thanks for all your help, very appreciated !

**Comment by allfro** [comment] 2019-02-25 21:15
Python expects each module directory to contain an `__init__.py` file. This is a convention that I do not control, unfortunately :). The `__init__.py` file can be used to export objects or can be left empty. It's really up to the module's author. It's not required to have any contents.

**Closed by allfro** 2019-02-25 21:15 UTC
Labels: question
